annotation:
  labels:
    - "Condition"
    - "Sensor"
    - "Other/Unknown"
data:
  # auto-slice imported data larger than this size (x axis)
  # data is still imported and can be shown, but is initially not plotted for performance reasons
  auto_truncate_size:
    100000
physiologicalinfo:
  # use these aliases for known phys. limits
  # high, low: float or None
  # aliases: list of strings, or empty list
  temperature:
    low: 25
    high: 45
    aliases: ["temp", "t", "c", "TempC"]
  heartrate:
    low: 15
    high: 230
    aliases: ["hr", "HR"]
  pamean:
    low: 1
    high: 98
    aliases: [ ]
  pasystolic:
    low: 5
    high: 140
    aliases: [ ]
  padiastolic:
    low: 1
    high: 93
    aliases: [ ]
  systemicmean:
    low: 25
    high: 210
    aliases: ["pMe"]
  systemicdiastolic:
    low: 20
    high: 180
    aliases: ["pDi"]
  systemicsystolic:
    low: 35
    high: 280
    aliases: ["pSy"]
  respiration:
    low: 4
    high: 65
    aliases: ["RR"]
  sao2:
    low: 20.5
    high: 100
    aliases: ["SaO2"]
  end-tidal-co2:
    low: 18
    high: 49
    aliases: ["etCO2"]
  central-venous-pressure:
    low: -10
    high: 50
    aliases: ["CVP"]
algorithms:
savestate:
plots:
  draw_outlier_series_box: True
  outlier_series_threshold: 5
  use_dark_mode: False

